// ...removed Google Fonts import...
import "./globals.css";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import Header from "../children/Header";
import Footer from "@/children/Footer";

// ...removed Google Fonts setup...

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = GeistSans;
const geistMono = GeistMono;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script src="https://cdn.tailwindcss.com"></script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header/>
        {children}
       <Footer/>

      </body>
    </html>
  );
}
